export type Product = {
  id: string;
  name: string;
  brand: string;
  category: string;
  categorySlug: string;
  price: number;
  mrp: number;
  rating: number;
  reviewCount: number;
  image: string;
  images: string[];
  badge?: string;
  energyRating?: string;
  specs: Record<string, string>;
  highlights: string[];
  prices: {
    store: string;
    price: number;
    url: string;
    delivery: string;
  }[];
  reviews: {
    id: string;
    author: string;
    rating: number;
    title: string;
    body: string;
    date: string;
    sentiment: 'positive' | 'negative' | 'neutral';
    verified: boolean;
  }[];
  sentiment: {
    positive: number;
    neutral: number;
    negative: number;
  };
};

export const products: Product[] = [
  // TVs
  {
    id: 'sony-bravia-x75l-55',
    name: 'Bravia X75L 55" 4K Ultra HD Smart LED TV',
    brand: 'Sony',
    category: 'TVs',
    categorySlug: 'tvs',
    price: 62990,
    mrp: 79900,
    rating: 4.3,
    reviewCount: 2847,
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f4834f?w=600&q=80',?fmt=pjpeg&wid=660&bgcolor=FFFFFF&bgc=FFFFFF',
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f4834f?w=600&q=80',
      'https://images.unsplash.com/photo-1593359677879-a4bb92f4834f?w=600&q=80',
    ],
    badge: 'Best Seller',
    energyRating: '4 Star',
    specs: {
      'Screen Size': '55 inches',
      'Resolution': '4K Ultra HD (3840x2160)',
      'Display Type': 'LED',
      'HDR': 'Dolby Vision, HDR10, HLG',
      'Processor': 'X1 4K HDR Processor',
      'Operating System': 'Google TV',
      'RAM': '2 GB',
      'Storage': '16 GB',
      'HDMI Ports': '4 (1x ARC)',
      'USB Ports': '2',
      'Wi-Fi': 'Wi-Fi 5 (802.11ac)',
      'Bluetooth': '5.0',
      'Sound Output': '20W',
      'Dolby Atmos': 'Yes',
      'Energy Rating': '4 Star BEE',
    },
    highlights: [
      'X1 4K HDR Processor for crystal clear picture',
      'Google TV with 700,000+ movies & shows',
      'Alexa, Google Assistant & Apple AirPlay 2',
      'BRAVIA CORE with 10 IMAX Enhanced titles',
      'Ambient Optimization for perfect picture in any room light',
    ],
    prices: [
      { store: 'Flipkart', price: 62990, url: 'https://www.flipkart.com/search?q=Sony+Bravia+X75L+55+inch+4K', delivery: 'Free delivery in 2 days' },
      { store: 'Amazon', price: 63990, url: 'https://www.amazon.in/s?k=Sony+Bravia+X75L+55+inch+4K+Smart+TV', delivery: 'Free delivery in 3 days' },
      { store: 'Croma', price: 64990, url: 'https://www.croma.com/searchB?q=Sony+Bravia+X75L+55', delivery: 'Same day delivery available' },
      { store: 'Reliance Digital', price: 65490, url: 'https://www.reliancedigital.in/search?q=Sony+Bravia+X75L+55', delivery: 'Free delivery in 4 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Rajesh Kumar', rating: 5, title: 'Superb picture quality!', body: 'Bought this during Diwali sale. The picture quality is just outstanding. Even during our frequent voltage fluctuations in Jaipur, it handles perfectly with its automatic voltage adjustment. Google TV is very smooth and loads apps quickly.', date: '2024-01-15', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Priya Mehta', rating: 5, title: 'Worth every rupee', body: 'After comparing with Samsung and LG, chose Sony for its X1 processor. The difference is visible especially during cricket matches. Dark scenes look amazing. HDMI ARC works perfectly with our soundbar. Very happy with the purchase from Croma.', date: '2024-02-20', sentiment: 'positive', verified: true },
      { id: 'r3', author: 'Arjun Sharma', rating: 4, title: 'Great TV but expensive', body: 'The Sony service center support is excellent. Had a minor issue with remote, they replaced it within 3 days without any questions. Picture quality is best in class. Only complaint is the price - wish Sony would be more competitive on pricing in India.', date: '2024-03-05', sentiment: 'positive', verified: true },
      { id: 'r4', author: 'Deepika Nair', rating: 2, title: 'Disappointed with smart features', body: 'The TV itself has good picture quality but Google TV is frustratingly slow at times. Also during summer heat waves in Chennai, the TV sometimes auto-shuts down. Sony support takes too long to respond. Expected better from a premium brand.', date: '2024-03-18', sentiment: 'negative', verified: true },
      { id: 'r5', author: 'Vikram Bhat', rating: 2, title: 'Remote issues after 6 months', body: 'The TV remote stopped working after 6 months. Service center said its a common issue but still took 2 weeks to replace. For 63,000 rupees, this is not acceptable. The picture is good but build quality concerns me.', date: '2024-04-02', sentiment: 'negative', verified: false },
      { id: 'r6', author: 'Anita Reddy', rating: 3, title: 'Average experience overall', body: 'Decent TV for the price. Colors are good. The built-in apps like Hotstar, Netflix work well. But the speaker quality is below par for a 63k TV. Need to invest in a soundbar. Setup was straightforward, delivery and installation by Flipkart was on time.', date: '2024-04-10', sentiment: 'neutral', verified: true },
    ],
    sentiment: { positive: 68, neutral: 17, negative: 15 },
  },
  {
    id: 'samsung-crystal-4k-55',
    name: 'Crystal 4K Pro 55" Smart LED TV (UA55CUE80BKLXL)',
    brand: 'Samsung',
    category: 'TVs',
    categorySlug: 'tvs',
    price: 54990,
    mrp: 72900,
    rating: 4.2,
    reviewCount: 3421,
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f4834f?w=600&q=80',/uhd-tv/crystal-4k-uhd-cu8000/UA55CU8000KLXL/UA55CU8000KLXL_001_Front_Black.jpg',
    images: [
      'https://images.samsung.com/in/televisions/uhd-tv/crystal-4k-uhd-cu8000/UA55CU8000KLXL/UA55CU8000KLXL_001_Front_Black.jpg',
      'https://images.samsung.com/in/televisions/uhd-tv/crystal-4k-uhd-cu8000/UA55CU8000KLXL/UA55CU8000KLXL_002_Back_Black.jpg',
    ],
    badge: 'Great Value',
    energyRating: '4 Star',
    specs: {
      'Screen Size': '55 inches',
      'Resolution': '4K Crystal UHD (3840x2160)',
      'Display Type': 'LED',
      'HDR': 'HDR10+, HLG',
      'Processor': 'Crystal 4K Processor',
      'Operating System': 'Tizen OS',
      'RAM': '1.5 GB',
      'Storage': '16 GB',
      'HDMI Ports': '3',
      'USB Ports': '1',
      'Wi-Fi': 'Wi-Fi 5',
      'Bluetooth': '4.2',
      'Sound Output': '20W',
      'Dolby Atmos': 'No',
      'Energy Rating': '4 Star BEE',
    },
    highlights: [
      'Crystal 4K Processor with AI Upscaling',
      'Tizen OS with SmartThings ecosystem',
      'Auto Game Mode with low input lag',
      'Multi Voice Assistant support',
      'Q-Symphony compatible',
    ],
    prices: [
      { store: 'Flipkart', price: 54990, url: 'https://www.flipkart.com/search?q=Samsung+Crystal+4K+55+inch+CU8000', delivery: 'Free delivery in 2 days' },
      { store: 'Amazon', price: 55490, url: 'https://www.amazon.in/s?k=Samsung+Crystal+4K+55+inch+Smart+TV', delivery: 'Free delivery in 2 days' },
      { store: 'Croma', price: 56990, url: 'https://www.croma.com/searchB?q=Samsung+Crystal+4K+55', delivery: 'Free delivery in 3 days' },
      { store: 'Reliance Digital', price: 57490, url: 'https://www.reliancedigital.in/search?q=Samsung+Crystal+4K+55+inch', delivery: 'Free delivery in 4 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Suresh Patel', rating: 5, title: 'Best Samsung TV I have owned', body: 'Third Samsung TV in our family and this is the best. Tizen OS is very smooth and all Indian OTT apps are pre-installed. During IPL, the auto game mode kicked in automatically. 4K content on Netflix and Disney+ looks breathtaking.', date: '2024-01-20', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Kavitha Krishnan', rating: 4, title: 'Good TV for the price', body: 'Compared with Sony Bravia in the showroom and chose Samsung because of the price difference. For everyday watching of serials and cricket, this is excellent. The screen is very bright and visible even with the harsh afternoon sun in our Hyderabad home.', date: '2024-02-14', sentiment: 'positive', verified: true },
      { id: 'r3', author: 'Manish Agarwal', rating: 4, title: 'Solid performer', body: 'The Samsung service network is the best in India, thats why I always choose Samsung. This TV delivers on its promise. Motion smoothing feature is great for cricket. Interface takes some getting used to but once you learn it, its very efficient.', date: '2024-03-01', sentiment: 'positive', verified: true },
      { id: 'r4', author: 'Sunita Yadav', rating: 2, title: 'Screen burn-in after 8 months', body: 'Started noticing slight burn-in where the news channel logo appears. Samsung service center said its not covered under warranty. For a nearly 55,000 rupee TV, this is unacceptable. Also the backlight bleeding is visible in dark rooms.', date: '2024-03-25', sentiment: 'negative', verified: true },
      { id: 'r5', author: 'Ravi Teja', rating: 2, title: 'Wi-Fi connectivity issues', body: 'Constantly drops Wi-Fi connection, have to restart the TV almost every day. The Samsung support suggested a firmware update but the issue persists. This is very frustrating. The picture quality is good but these connectivity issues are a deal breaker.', date: '2024-04-15', sentiment: 'negative', verified: true },
      { id: 'r6', author: 'Pallavi Singh', rating: 3, title: 'Decent but not great', body: 'For the price its acceptable. Doesnt have Dolby Atmos which my Sony had. The Crystal display is good in bright rooms but not as impressive in dark rooms. Smart features work well. Would recommend for a budget-conscious buyer.', date: '2024-04-22', sentiment: 'neutral', verified: true },
    ],
    sentiment: { positive: 65, neutral: 18, negative: 17 },
  },
  {
    id: 'lg-qned-55',
    name: 'QNED80 55" 4K Smart NanoCell TV (55QNED80TSA)',
    brand: 'LG',
    category: 'TVs',
    categorySlug: 'tvs',
    price: 71990,
    mrp: 95000,
    rating: 4.4,
    reviewCount: 1893,
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f4834f?w=600&q=80',/md07535050/gallery/medium01.jpg',
    images: [
      'https://www.lg.com/in/images/tvs/md07535050/gallery/medium01.jpg',
      'https://www.lg.com/in/images/tvs/md07535050/gallery/medium02.jpg',
    ],
    badge: "Editor's Choice",
    energyRating: '4 Star',
    specs: {
      'Screen Size': '55 inches',
      'Resolution': '4K Ultra HD (3840x2160)',
      'Display Type': 'QNED (NanoCell + Mini LED)',
      'HDR': 'Dolby Vision IQ, HDR10, HLG',
      'Processor': 'α7 Gen6 AI Processor 4K',
      'Operating System': 'webOS 23',
      'RAM': '2 GB',
      'Storage': '8 GB',
      'HDMI Ports': '4 (1x 4K 120Hz, 1x eARC)',
      'USB Ports': '2',
      'Wi-Fi': 'Wi-Fi 6 (802.11ax)',
      'Bluetooth': '5.0',
      'Sound Output': '40W (2.2ch)',
      'Dolby Atmos': 'Yes',
      'Energy Rating': '4 Star BEE',
    },
    highlights: [
      'α7 Gen6 AI Processor with Neural Processing Unit',
      'Quantum Dot NanoCell technology for wider color gamut',
      'webOS 23 with personalized ThinQ AI',
      'Filmmaker Mode for cinema-accurate picture',
      'Game Optimizer with VRR, ALLM, G-Sync Compatible',
    ],
    prices: [
      { store: 'Flipkart', price: 71990, url: 'https://www.flipkart.com/search?q=LG+QNED80+55+inch+4K', delivery: 'Free delivery in 3 days' },
      { store: 'Amazon', price: 72490, url: 'https://www.amazon.in/s?k=LG+QNED+55+inch+4K+Smart+TV', delivery: 'Free delivery in 2 days' },
      { store: 'Croma', price: 73990, url: 'https://www.croma.com/searchB?q=LG+QNED+55+inch', delivery: 'Same day delivery available' },
      { store: 'Reliance Digital', price: 74490, url: 'https://www.reliancedigital.in/search?q=LG+QNED+55+inch', delivery: 'Free delivery in 4 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Aditya Kumar', rating: 5, title: 'Best purchase of 2024', body: 'Upgraded from an old 40 inch LED to this QNED and the difference is night and day. The NanoCell technology makes colors pop without looking artificial. webOS is the most intuitive smart TV interface I have used. Even during power fluctuations in Pune, the TV recovered perfectly.', date: '2024-02-01', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Meera Iyer', rating: 5, title: 'Exceptional picture quality', body: 'Bought for our new home in Bangalore. The Filmmaker Mode is incredible for watching movies - colors are exactly as the director intended. LG ThinQ works seamlessly with our other LG appliances. The speakers are surprisingly good for a TV.', date: '2024-02-25', sentiment: 'positive', verified: true },
      { id: 'r3', author: 'Rohit Verma', rating: 4, title: 'Premium feel all around', body: 'The build quality and remote design are top notch. Magic Remote takes some time to master but then you cant go back to regular remotes. The only downside is the price - wish LG had made it more affordable for the Indian market.', date: '2024-03-12', sentiment: 'positive', verified: true },
      { id: 'r4', author: 'Shweta Gupta', rating: 2, title: 'Panel issue after 3 months', body: 'Bought for 72,000 and had a panel uniformity issue after 3 months. LG service took 15 days to acknowledge and then another month for the repair. During this entire process, our new TV was sitting broken. Customer service was unhelpful throughout.', date: '2024-03-28', sentiment: 'negative', verified: true },
      { id: 'r5', author: 'Kiran Babu', rating: 2, title: 'Overheating problem', body: 'The TV gets very hot on the left side, especially during long Netflix marathons. In the Hyderabad summer heat, this is concerning. Raised this with LG support and they said its normal. Paying premium money for a TV that runs hot seems wrong.', date: '2024-04-08', sentiment: 'negative', verified: false },
      { id: 'r6', author: 'Nisha Pillai', rating: 3, title: 'Good but had better expectations', body: 'The QNED display is good but not as revolutionary as the marketing suggests. When compared side by side with an OLED, the difference is stark. For movies and cricket, it performs well. The webOS is smooth. Price feels slightly high.', date: '2024-04-18', sentiment: 'neutral', verified: true },
    ],
    sentiment: { positive: 71, neutral: 14, negative: 15 },
  },
  {
    id: 'oneplus-y1s-pro-65',
    name: 'TV Y1S Pro 65" 4K Ultra HD Smart LED TV',
    brand: 'OnePlus',
    category: 'TVs',
    categorySlug: 'tvs',
    price: 49990,
    mrp: 64999,
    rating: 4.1,
    reviewCount: 4532,
    image: 'https://images.unsplash.com/photo-1571415060716-baff5f717c9d?w=600&q=80',/content/dam/oasis/page/2022/in/product/tv/y1s-pro/spec-image/65-inch.png',
    images: [
      'https://oasis.opstatics.com/content/dam/oasis/page/2022/in/product/tv/y1s-pro/spec-image/65-inch.png',
    ],
    badge: 'Best Budget',
    energyRating: '3 Star',
    specs: {
      'Screen Size': '65 inches',
      'Resolution': '4K Ultra HD (3840x2160)',
      'Display Type': 'LED',
      'HDR': 'HDR10, HLG',
      'Processor': 'Mediatek MT9652',
      'Operating System': 'Android TV 11',
      'RAM': '2 GB',
      'Storage': '16 GB',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'Wi-Fi': 'Wi-Fi 5 (Dual Band)',
      'Bluetooth': '5.0',
      'Sound Output': '30W (2.1ch)',
      'Dolby Atmos': 'Yes',
      'Energy Rating': '3 Star BEE',
    },
    highlights: [
      '65 inch screen at the price of 55 inch competitors',
      'Android TV 11 with Google Play Store access',
      'Gamma Engine for enhanced picture processing',
      '93% DCI-P3 color gamut coverage',
      'Works with OnePlus ecosystem devices',
    ],
    prices: [
      { store: 'Flipkart', price: 49990, url: 'https://www.flipkart.com/search?q=OnePlus+TV+Y1S+Pro+65+inch', delivery: 'Free delivery in 2 days' },
      { store: 'Amazon', price: 51490, url: 'https://www.amazon.in/s?k=OnePlus+TV+Y1S+Pro+65+inch', delivery: 'Free delivery in 3 days' },
      { store: 'Croma', price: 52990, url: 'https://www.croma.com/searchB?q=OnePlus+TV+Y1S+Pro+65', delivery: 'Free delivery in 4 days' },
      { store: 'Reliance Digital', price: 53490, url: 'https://www.reliancedigital.in/search?q=OnePlus+TV+Y1S+Pro+65', delivery: 'Free delivery in 4 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Gaurav Tiwari', rating: 5, title: 'Unbeatable value for money', body: 'Got 65 inches for under 50,000! The picture quality rivals my friends 55 inch Sony. Android TV means all apps work perfectly. Cricket on this huge screen is an amazing experience. Highly recommend for those on a budget.', date: '2024-01-28', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Pooja Acharya', rating: 4, title: 'Great screen, average software', body: 'The display and audio are excellent for the price. However, Android TV sometimes shows too many ads and bloatware. OnePlus should offer a cleaner software experience. Overall a good purchase if you primarily use streaming apps.', date: '2024-02-18', sentiment: 'positive', verified: true },
      { id: 'r3', author: 'Sanjay Mishra', rating: 4, title: 'Perfect for the budget', body: 'Our family of 6 watches cricket, serials and movies on this. The 65 inch size is perfect for our large living room. The sound is better than expected. Remote control feels cheap but the TV itself is solid. OnePlus has really impressed us.', date: '2024-03-08', sentiment: 'positive', verified: true },
      { id: 'r4', author: 'Rekha Nambiar', rating: 2, title: 'Remote stopped working in 2 months', body: 'The TV is good but the remote stopped working after 2 months. OnePlus service center in our city (Kochi) is very hard to find. Had to travel 30 km for service. The software also tends to freeze occasionally. Not the quality I expected.', date: '2024-03-22', sentiment: 'negative', verified: true },
      { id: 'r5', author: 'Dhruv Sharma', rating: 1, title: 'Panel dead after 10 months', body: 'The LED panel had dead pixels and finally gave up after 10 months. OnePlus warranty process is very complicated. They are asking me to ship the TV to service center which is practically impossible for a 65 inch TV. Very disappointed.', date: '2024-04-12', sentiment: 'negative', verified: true },
      { id: 'r6', author: 'Mamta Joshi', rating: 3, title: 'Okay for the price', body: 'If you compare it with Sony or Samsung, it falls short in picture quality and software smoothness. But for the price, it is acceptable. My kids use it for YouTube and gaming mostly. Delivery was quick, installation was free and professional.', date: '2024-04-25', sentiment: 'neutral', verified: true },
    ],
    sentiment: { positive: 62, neutral: 19, negative: 19 },
  },
  {
    id: 'mi-tv-5x-55',
    name: 'TV 5X 55" 4K Ultra HD Smart Android TV',
    brand: 'Xiaomi',
    category: 'TVs',
    categorySlug: 'tvs',
    price: 44990,
    mrp: 56999,
    rating: 4.0,
    reviewCount: 6234,
    image: 'https://images.unsplash.com/photo-1571415060716-baff5f717c9d?w=600&q=80',/mi-com-product/fly-birds/mi-tv-5x/M/9e4c45b68fac61e942d9476c1cabd8f9.png',
    images: [
      'https://i02.appmifile.com/mi-com-product/fly-birds/mi-tv-5x/M/9e4c45b68fac61e942d9476c1cabd8f9.png',
    ],
    badge: 'Most Popular',
    energyRating: '3 Star',
    specs: {
      'Screen Size': '55 inches',
      'Resolution': '4K Ultra HD (3840x2160)',
      'Display Type': 'LED',
      'HDR': 'HDR10, HLG, Dolby Vision',
      'Processor': 'MediaTek MT9611',
      'Operating System': 'PatchWall + Android TV 10',
      'RAM': '2 GB',
      'Storage': '32 GB',
      'HDMI Ports': '3',
      'USB Ports': '2',
      'Wi-Fi': 'Wi-Fi 5 (Dual Band)',
      'Bluetooth': '5.0',
      'Sound Output': '30W (2.1ch)',
      'Dolby Atmos': 'Yes',
      'Energy Rating': '3 Star BEE',
    },
    highlights: [
      'PatchWall AI-powered content discovery',
      '32GB onboard storage, largest in class',
      'Dolby Vision + Dolby Atmos support',
      'Far-field microphone for hands-free voice control',
      'Vivid Picture Engine for enhanced clarity',
    ],
    prices: [
      { store: 'Flipkart', price: 44990, url: 'https://www.flipkart.com/search?q=Mi+TV+5X+55+inch+4K', delivery: 'Free delivery in 2 days' },
      { store: 'Amazon', price: 45990, url: 'https://www.amazon.in/s?k=Mi+TV+5X+55+inch+4K+Android+TV', delivery: 'Free delivery in 3 days' },
      { store: 'Croma', price: 47490, url: 'https://www.croma.com/searchB?q=Mi+TV+5X+55+inch', delivery: 'Free delivery in 4 days' },
      { store: 'Reliance Digital', price: 46990, url: 'https://www.reliancedigital.in/search?q=Mi+TV+5X+55+inch', delivery: 'Free delivery in 3 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Amit Kapoor', rating: 4, title: 'Great budget TV', body: 'Mi 5X is the best budget TV available. PatchWall is innovative and content discovery is excellent. Dolby Vision at this price is incredible. Family loves it. The 32GB storage is very useful for downloading apps.', date: '2024-02-10', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Vandana Pillai', rating: 4, title: 'Impressive features at affordable price', body: 'Compared with Realme and TCL TVs before buying this. Mi 5X wins hands down in features and build quality. PatchWall occasionally shows ads which is annoying but overall a solid performer. Delivery and setup was hassle-free.', date: '2024-03-05', sentiment: 'positive', verified: true },
      { id: 'r3', author: 'Nikhil Jain', rating: 2, title: 'Service is terrible', body: 'TV stopped working after 8 months. Mi service center says it will take 3-4 weeks for repair. No loan device provided. The customer care number is almost impossible to get through. Xiaomi products have good hardware but terrible after-sales service in smaller cities.', date: '2024-03-30', sentiment: 'negative', verified: true },
      { id: 'r4', author: 'Seema Kapoor', rating: 3, title: 'Average overall', body: 'Gets the job done for daily use. PatchWall shows too many ads which is irritating. The picture quality is decent but not impressive in bright daylight. Our living room faces east and the morning sun washes out the screen. Would buy again only if price drops further.', date: '2024-04-20', sentiment: 'neutral', verified: false },
    ],
    sentiment: { positive: 59, neutral: 21, negative: 20 },
  },
  // Refrigerators
  {
    id: 'samsung-french-door-653',
    name: '653L French Door Refrigerator with SpaceMax',
    brand: 'Samsung',
    category: 'Refrigerators',
    categorySlug: 'refrigerators',
    price: 129990,
    mrp: 165000,
    rating: 4.5,
    reviewCount: 892,
    image: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&q=80',/french-door-refrigerators/653l-french-door-rf65a977fsrhl/RF65A977FSR_HL_001_Front_Silver.jpg',
    images: [
      'https://images.samsung.com/in/refrigerators/french-door-refrigerators/653l-french-door-rf65a977fsrhl/RF65A977FSR_HL_001_Front_Silver.jpg',
    ],
    badge: 'Premium Pick',
    energyRating: '5 Star',
    specs: {
      'Capacity': '653 Litres',
      'Type': 'French Door',
      'Compressor': 'Digital Inverter',
      'Energy Rating': '5 Star BEE',
      'Annual Power Consumption': '312 kWh',
      'Cooling Technology': 'SpaceMax Technology',
      'Smart Diagnosis': 'Yes (SmartThings App)',
      'Door Alarm': 'Yes',
      'Auto Defrost': 'Yes',
      'Warranty': '1 Year Comprehensive + 10 Years Compressor',
    },
    highlights: [
      'SpaceMax technology maximizes storage without increasing external dimensions',
      'Metal Cooling Door retains cold air even during power cuts',
      'Digital Inverter Compressor adapts cooling based on food load',
      'FlexZone drawer converts between fridge and freezer',
      'Twin Cooling Plus keeps humidity optimal',
    ],
    prices: [
      { store: 'Flipkart', price: 129990, url: 'https://www.flipkart.com/search?q=Samsung+653L+French+Door+Refrigerator', delivery: 'Free delivery in 5 days' },
      { store: 'Amazon', price: 131990, url: 'https://www.amazon.in/s?k=Samsung+653L+French+Door+Refrigerator', delivery: 'Free delivery in 4 days' },
      { store: 'Croma', price: 132990, url: 'https://www.croma.com/searchB?q=Samsung+French+Door+653L', delivery: 'Same day delivery available' },
      { store: 'Reliance Digital', price: 134990, url: 'https://www.reliancedigital.in/search?q=Samsung+French+Door+653L+Refrigerator', delivery: 'Free delivery in 6 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Lalit Agrawal', rating: 5, title: 'Worth every paisa', body: 'Bought this for our new home. The SpaceMax technology is real - we can fit so much more than our old 450L fridge. During the Delhi summer, even in 45 degree heat, it maintains temperature perfectly. The metal cooling door is a game changer during our frequent power cuts.', date: '2024-01-10', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Madhuri Rao', rating: 5, title: 'Excellent for large families', body: 'Our joint family of 10 struggled with two separate fridges before this. Now everything fits in this one. The FlexZone is perfect for changing between ice cream mode and chilling drinks during summer parties. Very impressed with Samsung quality.', date: '2024-02-12', sentiment: 'positive', verified: true },
      { id: 'r3', author: 'Pawan Gupta', rating: 2, title: 'Compressor noise issue', body: 'The compressor makes a loud grinding noise every time it starts. Samsung technician visited and said its within acceptable limits but its clearly louder than normal. At 1.3 lakh, I expect silent operation. Service response was slow.', date: '2024-03-20', sentiment: 'negative', verified: true },
    ],
    sentiment: { positive: 78, neutral: 12, negative: 10 },
  },
  {
    id: 'lg-688l-fridge',
    name: '688L Side-by-Side Refrigerator with InstaView',
    brand: 'LG',
    category: 'Refrigerators',
    categorySlug: 'refrigerators',
    price: 115990,
    mrp: 149000,
    rating: 4.3,
    reviewCount: 654,
    image: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&q=80',/md07519888/gallery/medium01.jpg',
    images: [
      'https://www.lg.com/in/images/refrigerators/md07519888/gallery/medium01.jpg',
    ],
    badge: 'Top Rated',
    energyRating: '5 Star',
    specs: {
      'Capacity': '688 Litres',
      'Type': 'Side-by-Side',
      'Compressor': 'Linear Inverter',
      'Energy Rating': '5 Star BEE',
      'Annual Power Consumption': '287 kWh',
      'Cooling Technology': 'DoorCooling+ with InstaView',
      'Smart Diagnosis': 'Yes (ThinQ App)',
      'Door Alarm': 'Yes',
      'Auto Defrost': 'Yes',
      'Warranty': '1 Year Comprehensive + 10 Years Compressor',
    },
    highlights: [
      'InstaView door-in-door with knock-to-see technology',
      'DoorCooling+ for 32% faster cooling',
      'Linear Inverter Compressor - 25% more energy efficient',
      'Hygiene Fresh+ air filter removes 99.9% bacteria',
      'ThinQ app for remote temperature control',
    ],
    prices: [
      { store: 'Flipkart', price: 115990, url: 'https://www.flipkart.com/search?q=LG+688L+Side+by+Side+InstaView+Refrigerator', delivery: 'Free delivery in 5 days' },
      { store: 'Amazon', price: 117490, url: 'https://www.amazon.in/s?k=LG+688L+Side+by+Side+InstaView+Refrigerator', delivery: 'Free delivery in 4 days' },
      { store: 'Croma', price: 119990, url: 'https://www.croma.com/searchB?q=LG+688L+Side+by+Side+Refrigerator', delivery: 'Same day delivery available' },
      { store: 'Reliance Digital', price: 120990, url: 'https://www.reliancedigital.in/search?q=LG+688L+InstaView+Refrigerator', delivery: 'Free delivery in 6 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Hemant Shinde', rating: 5, title: 'InstaView is magical', body: 'The knock-to-see InstaView panel is genuinely useful. We tap twice and see whats inside without opening the door. In Mumbai summers this saves so much cold air. The compressor is whisper quiet. LG quality never disappoints.', date: '2024-02-05', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Divya Menon', rating: 2, title: 'Delivery damaged the unit', body: 'The delivered unit had a dent on the door. LG customer care took 3 weeks to arrange a replacement. The new unit works fine but the process was very frustrating. Make sure you inspect thoroughly before the delivery person leaves.', date: '2024-03-15', sentiment: 'negative', verified: true },
    ],
    sentiment: { positive: 74, neutral: 13, negative: 13 },
  },
  {
    id: 'haier-320l-fridge',
    name: '320L Double Door Refrigerator (HEF-323FSGS)',
    brand: 'Haier',
    category: 'Refrigerators',
    categorySlug: 'refrigerators',
    price: 32990,
    mrp: 43000,
    rating: 4.1,
    reviewCount: 1243,
    image: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80',/in/content/dam/haier/in/productcatalog/refrigerators/double-door/HRB-3404PKG-E/HRB-3404PKG-E.png',
    images: [
      'https://www.haier.com/in/content/dam/haier/in/productcatalog/refrigerators/double-door/HRB-3404PKG-E/HRB-3404PKG-E.png',
    ],
    badge: 'Budget Pick',
    energyRating: '3 Star',
    specs: {
      'Capacity': '320 Litres',
      'Type': 'Double Door (Top Freezer)',
      'Compressor': 'Twin Inverter',
      'Energy Rating': '3 Star BEE',
      'Annual Power Consumption': '258 kWh',
      'Cooling Technology': '10-in-1 Convertible',
      'Smart Diagnosis': 'No',
      'Door Alarm': 'Yes',
      'Auto Defrost': 'Yes',
      'Warranty': '1 Year Comprehensive + 10 Years Compressor',
    },
    highlights: [
      '10-in-1 Convertible Refrigerator adapts to your needs',
      'Nano Cool Technology works in 62°C ambient temperature',
      'Twin Inverter Technology saves electricity',
      'Corner edge design maximizes storage space',
      'Certified for Indian voltage fluctuations (100V-290V)',
    ],
    prices: [
      { store: 'Flipkart', price: 32990, url: 'https://www.flipkart.com/search?q=Haier+320L+Double+Door+Refrigerator', delivery: 'Free delivery in 3 days' },
      { store: 'Amazon', price: 33490, url: 'https://www.amazon.in/s?k=Haier+320L+Double+Door+Refrigerator', delivery: 'Free delivery in 4 days' },
      { store: 'Croma', price: 34990, url: 'https://www.croma.com/searchB?q=Haier+320L+Refrigerator', delivery: 'Free delivery in 3 days' },
      { store: 'Reliance Digital', price: 34490, url: 'https://www.reliancedigital.in/search?q=Haier+320L+Double+Door+Refrigerator', delivery: 'Free delivery in 4 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Ramesh Choudhary', rating: 4, title: 'Perfect for Indian conditions', body: 'Haier has specially designed this for Indian conditions and it shows. Even during Rajasthan summer at 48 degrees, it keeps everything chilled. The voltage fluctuation protection is excellent for our area. Very satisfied with the purchase.', date: '2024-01-25', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Jyoti Verma', rating: 2, title: 'Plastic quality is cheap', body: 'The fridge works but the plastic build quality feels very cheap for the price. The vegetable compartment drawer already has cracks after 4 months. Haier needs to improve their build quality if they want to compete with Samsung and LG.', date: '2024-03-10', sentiment: 'negative', verified: true },
    ],
    sentiment: { positive: 63, neutral: 20, negative: 17 },
  },
  // ACs
  {
    id: 'daikin-1-5t-5star',
    name: '1.5 Ton 5 Star Inverter Split AC (FTKF50TV16U)',
    brand: 'Daikin',
    category: 'Air Conditioners',
    categorySlug: 'air-conditioners',
    price: 52990,
    mrp: 69000,
    rating: 4.6,
    reviewCount: 3892,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80',/content/dam/daikin/in/products/split/FTKF50TV16U/FTKF50TV16U_indoor.png',
    images: [
      'https://www.daikin.co.in/content/dam/daikin/in/products/split/FTKF50TV16U/FTKF50TV16U_indoor.png',
    ],
    badge: 'Most Reliable',
    energyRating: '5 Star',
    specs: {
      'Capacity': '1.5 Ton',
      'Type': 'Split AC',
      'Inverter': 'Yes',
      'Energy Rating': '5 Star ISEER',
      'ISEER': '5.20',
      'Cooling Capacity': '5050W',
      'Auto Restart': 'Yes',
      'Refrigerant': 'R-32 (eco-friendly)',
      'PM 2.5 Filter': 'Yes',
      'Voltage Stabilizer': 'Built-in (160V-240V)',
      'Warranty': '1 Year + 5 Years Compressor',
    },
    highlights: [
      'Coanda Airflow technology for uniform room cooling',
      'Built-in voltage protection - no separate stabilizer needed',
      'R-32 refrigerant - 68% lower global warming potential',
      'Works in extreme temperatures up to 50°C ambient',
      'Self-cleaning function prevents mold and bacteria',
    ],
    prices: [
      { store: 'Flipkart', price: 52990, url: 'https://www.flipkart.com/search?q=Daikin+1.5+Ton+5+Star+Inverter+Split+AC', delivery: 'Free delivery in 3 days' },
      { store: 'Amazon', price: 53490, url: 'https://www.amazon.in/s?k=Daikin+1.5+Ton+5+Star+Inverter+Split+AC', delivery: 'Free delivery in 4 days' },
      { store: 'Croma', price: 54990, url: 'https://www.croma.com/searchB?q=Daikin+1.5+Ton+5+Star+AC', delivery: 'Same day delivery available' },
      { store: 'Reliance Digital', price: 54490, url: 'https://www.reliancedigital.in/search?q=Daikin+1.5+Ton+5+Star+Inverter+AC', delivery: 'Free delivery in 5 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Vinod Khanna', rating: 5, title: 'Best AC for Indian summers', body: 'Third Daikin AC in our home and they have all been absolutely reliable. This one handles Nagpur summer (47 degrees!) without breaking a sweat. The 5 star rating is real - our electricity bills went down 30% compared to our old 3 star AC. Worth the premium.', date: '2024-01-08', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Kamala Subramaniam', rating: 5, title: 'Silent and efficient', body: 'The Coanda airflow is incredible - the entire bedroom cools evenly within 10 minutes even in Chennai summer. No more fighting over who sits near the AC! The built-in voltage protection is a relief as our area has frequent fluctuations. Daikin is the gold standard.', date: '2024-02-16', sentiment: 'positive', verified: true },
      { id: 'r3', author: 'Farhan Siddiqui', rating: 2, title: 'Installation team was terrible', body: 'The AC itself is good but the authorized installer who came through the dealer was very unprofessional. Made extra holes in the wall, did a messy piping job. Daikin should ensure better installation standards. The AC performance is good but the installation experience ruined it.', date: '2024-03-28', sentiment: 'negative', verified: true },
    ],
    sentiment: { positive: 82, neutral: 10, negative: 8 },
  },
  {
    id: 'voltas-1-8t-inverter',
    name: '1.8 Ton 3 Star Inverter Split AC (213V Vectra Prism)',
    brand: 'Voltas',
    category: 'Air Conditioners',
    categorySlug: 'air-conditioners',
    price: 45990,
    mrp: 58000,
    rating: 4.2,
    reviewCount: 2341,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80',/content/dam/voltas/in/products/air-conditioners/split/213V-Vectra-Prism/213V-Vectra-Prism-front.png',
    images: [
      'https://www.voltasindia.com/content/dam/voltas/in/products/air-conditioners/split/213V-Vectra-Prism/213V-Vectra-Prism-front.png',
    ],
    badge: 'Indian Brand',
    energyRating: '3 Star',
    specs: {
      'Capacity': '1.8 Ton',
      'Type': 'Split AC',
      'Inverter': 'Yes',
      'Energy Rating': '3 Star ISEER',
      'ISEER': '3.80',
      'Cooling Capacity': '5750W',
      'Auto Restart': 'Yes',
      'Refrigerant': 'R-32',
      'PM 2.5 Filter': 'Yes',
      'Voltage Stabilizer': 'Built-in (135V-280V)',
      'Warranty': '1 Year + 5 Years Compressor',
    },
    highlights: [
      'Tata Group company - strong pan-India service network',
      'Works in -15°C to +54°C ambient temperature',
      'Active Dehumidifier for Indian monsoon',
      'Auto Adjustable Inverter for Indian voltage fluctuations',
      'Dust Filter + Anti-bacterial coating',
    ],
    prices: [
      { store: 'Flipkart', price: 45990, url: 'https://www.flipkart.com/search?q=Voltas+1.8+Ton+3+Star+Inverter+Split+AC', delivery: 'Free delivery in 3 days' },
      { store: 'Amazon', price: 46990, url: 'https://www.amazon.in/s?k=Voltas+1.8+Ton+Inverter+Split+AC', delivery: 'Free delivery in 3 days' },
      { store: 'Croma', price: 47490, url: 'https://www.croma.com/searchB?q=Voltas+1.8+Ton+Inverter+AC', delivery: 'Same day delivery available' },
      { store: 'Reliance Digital', price: 47990, url: 'https://www.reliancedigital.in/search?q=Voltas+1.8+Ton+Inverter+Split+AC', delivery: 'Free delivery in 5 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Shankar Rao', rating: 4, title: 'Reliable Tata product', body: 'Chose Voltas specifically because of Tata service network in our tier-2 city. Service centers are everywhere and response time is excellent. The 1.8 ton cools our large 250 sqft master bedroom perfectly even in peak Hyderabad summer.', date: '2024-02-08', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Bindu Thomas', rating: 2, title: 'Noise level is unacceptable', body: 'The outdoor unit makes a very loud noise especially in heat mode. Neighbors have complained multiple times. Voltas technician said its within normal limits but it clearly is not. The cooling performance is decent but the noise is a deal breaker.', date: '2024-03-18', sentiment: 'negative', verified: true },
    ],
    sentiment: { positive: 70, neutral: 16, negative: 14 },
  },
  // Washing Machines
  {
    id: 'lg-8kg-front-load',
    name: '8 kg 5 Star Wi-Fi AI Direct Drive Front Load Washing Machine',
    brand: 'LG',
    category: 'Washing Machines',
    categorySlug: 'washing-machines',
    price: 55990,
    mrp: 73000,
    rating: 4.5,
    reviewCount: 2156,
    image: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&q=80',/md07534206/gallery/medium01.jpg',
    images: [
      'https://www.lg.com/in/images/washing-machines/md07534206/gallery/medium01.jpg',
    ],
    badge: 'Best Front Load',
    energyRating: '5 Star',
    specs: {
      'Capacity': '8 kg',
      'Type': 'Front Load',
      'Spin Speed': '1400 RPM',
      'Energy Rating': '5 Star BEE',
      'Wash Programs': '22',
      'Motor': 'AI Direct Drive (10 Year Warranty)',
      'Wi-Fi': 'Yes (ThinQ App)',
      'Steam Wash': 'Yes',
      'Child Lock': 'Yes',
      'Drum Material': 'Stainless Steel',
      'Water Inlet': 'Cold & Hot',
      'Warranty': '2 Years Comprehensive + 10 Years Motor',
    },
    highlights: [
      'AI Direct Drive motor detects fabric type and adjusts wash cycle',
      'Steam+ function removes 99.9% allergens including Indian dust and pollen',
      'ThinQ app - download new wash programs, remote control',
      '6 Motion technology mimics handwashing for delicate fabrics',
      'Turbo Wash 360 for complete cleaning in 39 minutes',
    ],
    prices: [
      { store: 'Flipkart', price: 55990, url: 'https://www.flipkart.com/search?q=LG+8kg+5+Star+AI+Direct+Drive+Front+Load+Washing+Machine', delivery: 'Free delivery in 3 days' },
      { store: 'Amazon', price: 56990, url: 'https://www.amazon.in/s?k=LG+8kg+Front+Load+AI+Direct+Drive+Washing+Machine', delivery: 'Free delivery in 4 days' },
      { store: 'Croma', price: 57990, url: 'https://www.croma.com/searchB?q=LG+8kg+Front+Load+Washing+Machine', delivery: 'Same day delivery available' },
      { store: 'Reliance Digital', price: 58490, url: 'https://www.reliancedigital.in/search?q=LG+8kg+Front+Load+Washing+Machine', delivery: 'Free delivery in 5 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Nalini Krishnamurthy', rating: 5, title: 'Life changing appliance', body: 'After years of semi-automatic washing, switching to this LG front loader changed our lives. The AI Direct Drive detects fabric perfectly - our silk sarees come out pristine. The steam function actually removed the turmeric stains from our cotton kurtas! Incredible.', date: '2024-01-20', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Saurabh Pathak', rating: 5, title: 'Worth the premium price', body: 'The ThinQ app is genuinely useful. I start a wash cycle from office and clothes are ready when I reach home. The 10 year motor warranty gives great peace of mind. LG quality is consistently excellent. The water consumption is also very efficient.', date: '2024-02-22', sentiment: 'positive', verified: true },
      { id: 'r3', author: 'Geeta Ahuja', rating: 2, title: 'Vibrates excessively', body: 'The machine vibrates and moves during spin cycle. On our first floor, the neighbors below can hear it. LG service said the flooring is the issue but other machines on same floor dont vibrate. For a premium washing machine at 56,000, this should not happen.', date: '2024-04-05', sentiment: 'negative', verified: true },
    ],
    sentiment: { positive: 79, neutral: 12, negative: 9 },
  },
  {
    id: 'samsung-7kg-front-load',
    name: '7 kg 5 Star Inverter Front Load Washing Machine (WW70T4020CE)',
    brand: 'Samsung',
    category: 'Washing Machines',
    categorySlug: 'washing-machines',
    price: 48990,
    mrp: 62000,
    rating: 4.3,
    reviewCount: 1876,
    image: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&q=80',/front-load-washing-machine/7-kg-ecobubble-ww70t4020cehl/WW70T4020CE_HL_001_Front_White.jpg',
    images: [
      'https://images.samsung.com/in/washing-machines/front-load-washing-machine/7-kg-ecobubble-ww70t4020cehl/WW70T4020CE_HL_001_Front_White.jpg',
    ],
    badge: 'Great Buy',
    energyRating: '5 Star',
    specs: {
      'Capacity': '7 kg',
      'Type': 'Front Load',
      'Spin Speed': '1200 RPM',
      'Energy Rating': '5 Star BEE',
      'Wash Programs': '15',
      'Motor': 'Digital Inverter (5 Year Warranty)',
      'Wi-Fi': 'No',
      'Steam Wash': 'No',
      'Child Lock': 'Yes',
      'Drum Material': 'Stainless Steel (Diamond Drum)',
      'Water Inlet': 'Cold Only',
      'Warranty': '3 Years Comprehensive + 5 Years Motor',
    },
    highlights: [
      'Diamond Drum with unique swirl pattern to protect fabrics',
      'EcoBubble technology for effective washing in cold water',
      'Digital Inverter Motor - quieter, more efficient, longer lasting',
      'Hygiene Steam function reduces bacteria',
      'Add Garment feature - pause and add missed items',
    ],
    prices: [
      { store: 'Flipkart', price: 48990, url: 'https://www.flipkart.com/search?q=Samsung+7kg+5+Star+EcoBubble+Front+Load+Washing+Machine', delivery: 'Free delivery in 2 days' },
      { store: 'Amazon', price: 49490, url: 'https://www.amazon.in/s?k=Samsung+7kg+Front+Load+EcoBubble+Washing+Machine', delivery: 'Free delivery in 3 days' },
      { store: 'Croma', price: 50990, url: 'https://www.croma.com/searchB?q=Samsung+7kg+Front+Load+Washing+Machine', delivery: 'Same day delivery available' },
      { store: 'Reliance Digital', price: 51490, url: 'https://www.reliancedigital.in/search?q=Samsung+7kg+Front+Load+Washing+Machine', delivery: 'Free delivery in 4 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Preethi Nair', rating: 4, title: 'Excellent cleaning performance', body: 'The EcoBubble technology actually works! Washes in cold water and clothes come out perfectly clean. Great for areas with water quality issues - the bubble technology seems to compensate for hard water. Samsung quality is consistently good.', date: '2024-02-14', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Akash Dubey', rating: 2, title: 'Control panel stopped working', body: 'The touch control panel became unresponsive after 7 months. Samsung service took 3 weeks to fix and charged me for a part even though it was within warranty. The repair quality is also questionable. Very disappointed with after-sales.', date: '2024-04-01', sentiment: 'negative', verified: true },
    ],
    sentiment: { positive: 72, neutral: 14, negative: 14 },
  },
  // Water Purifiers
  {
    id: 'kent-grand-plus',
    name: 'Grand Plus RO+UV+UF+TDS Controller Water Purifier',
    brand: 'Kent',
    category: 'Water Purifiers',
    categorySlug: 'water-purifiers',
    price: 16990,
    mrp: 20990,
    rating: 4.4,
    reviewCount: 15432,
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=600&q=80',/images/products/kent-grand-plus-water-purifier.jpg',
    images: [
      'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=600&q=80',
    ],
    badge: "India's #1",
    energyRating: '',
    specs: {
      'Purification Method': 'RO + UV + UF + TDS Controller',
      'Storage Capacity': '8 Litres',
      'Purification Capacity': '20 Litres/hour',
      'TDS Reduction': 'Up to 2000 ppm inlet',
      'UV LED': 'Yes',
      'In-tank Purification': 'Yes',
      'Filter Life': '2000 Litres per filter set',
      'Installation': 'Wall Mounted',
      'Power': '60W',
      'Warranty': '1 Year + Free Installation',
    },
    highlights: [
      'Multiple purification for 99.9% pure water',
      'Double Purification - purifies stored water automatically',
      'TDS controller retains essential minerals',
      'Alerts for filter change, UV fail, tank full',
      'Zero Water Wastage technology (saves 50% water vs standard RO)',
    ],
    prices: [
      { store: 'Flipkart', price: 16990, url: 'https://www.flipkart.com/search?q=Kent+Grand+Plus+RO+Water+Purifier', delivery: 'Free delivery in 3 days' },
      { store: 'Amazon', price: 17490, url: 'https://www.amazon.in/s?k=Kent+Grand+Plus+RO+UV+Water+Purifier', delivery: 'Free delivery in 4 days' },
      { store: 'Croma', price: 17990, url: 'https://www.croma.com/searchB?q=Kent+Grand+Plus+Water+Purifier', delivery: 'Free delivery in 3 days' },
      { store: 'Reliance Digital', price: 17990, url: 'https://www.reliancedigital.in/search?q=Kent+Grand+Plus+Water+Purifier', delivery: 'Free delivery in 5 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Mohan Lal', rating: 5, title: 'Best water purifier for Indian water', body: 'Living in an area with TDS of 1500+ (Rajasthan), Kent Grand Plus is the only purifier that handles our water quality. The TDS controller ensures we get minerals while removing all the bad stuff. 5 years and still going strong.', date: '2024-01-12', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Kavya Reddy', rating: 4, title: 'Handles Hyderabad hard water perfectly', body: 'Hyderabad water is notoriously hard and this Kent handles it excellently. The output water tastes much better than packaged water. Filter replacement is easy to do yourself. Kent service network is excellent with next-day AMC service.', date: '2024-02-28', sentiment: 'positive', verified: true },
      { id: 'r3', author: 'Tarun Mehta', rating: 2, title: 'AMC charges are daylight robbery', body: 'The purifier works well but Kent AMC charges are extremely high. They charge ₹3,500 for annual maintenance which includes overpriced filters. And they refuse to service if you dont take their AMC. The machine performance is good but the after-sales business model is exploitative.', date: '2024-03-25', sentiment: 'negative', verified: true },
    ],
    sentiment: { positive: 75, neutral: 13, negative: 12 },
  },
  {
    id: 'aquaguard-aura',
    name: 'Aura RO+UV+MTDS Water Purifier with 8-Stage Purification',
    brand: 'Aquaguard',
    category: 'Water Purifiers',
    categorySlug: 'water-purifiers',
    price: 19990,
    mrp: 24990,
    rating: 4.3,
    reviewCount: 8921,
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=600&q=80',/images/products/aura/aquaguard-aura-ro-uv-mtds.jpg',
    images: [
      'https://www.aquaguard.com/images/products/aura/aquaguard-aura-ro-uv-mtds.jpg',
    ],
    badge: 'Trusted Brand',
    energyRating: '',
    specs: {
      'Purification Method': 'RO + UV + MTDS',
      'Storage Capacity': '7 Litres',
      'Purification Capacity': '25 Litres/hour',
      'TDS Reduction': 'Up to 2000 ppm inlet',
      'Mineral Fortification': 'Yes',
      'Taste Enhancer': 'Yes',
      'Auto UV Fail Alert': 'Yes',
      'Installation': 'Wall Mounted / Counter Top',
      'Power': '55W',
      'Warranty': '1 Year + Free Installation + 3 Free Services',
    },
    highlights: [
      '8-stage purification for the purest water',
      'Mineral Fortification adds calcium and magnesium',
      'IntelliSense technology with auto service reminders',
      'Active Copper Technology for added health benefits',
      'Aquaguard has 4 million+ happy customers in India',
    ],
    prices: [
      { store: 'Flipkart', price: 19990, url: 'https://www.flipkart.com/search?q=Aquaguard+Aura+RO+UV+Water+Purifier', delivery: 'Free delivery in 3 days' },
      { store: 'Amazon', price: 20490, url: 'https://www.amazon.in/s?k=Aquaguard+Aura+RO+UV+MTDS+Water+Purifier', delivery: 'Free delivery in 4 days' },
      { store: 'Croma', price: 21990, url: 'https://www.croma.com/searchB?q=Aquaguard+Aura+Water+Purifier', delivery: 'Free delivery in 3 days' },
      { store: 'Reliance Digital', price: 21490, url: 'https://www.reliancedigital.in/search?q=Aquaguard+Aura+Water+Purifier', delivery: 'Free delivery in 5 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Subhash Nair', rating: 5, title: 'Best brand for purifier in Kerala', body: 'Aquaguard has been our family choice for 15 years. This new Aura model is excellent. The mineral fortification is important as Kerala water is low in minerals after purification. Taste is excellent. Service is very prompt - usually same day in our area.', date: '2024-01-30', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Sonia Rastogi', rating: 2, title: 'Flow rate dropped after 6 months', body: 'The water flow rate dropped significantly after 6 months. Aquaguard technician said membrane needs replacement which costs ₹3,200. This is too soon for a membrane to fail. The product quality is not matching its premium pricing anymore.', date: '2024-04-10', sentiment: 'negative', verified: true },
    ],
    sentiment: { positive: 73, neutral: 14, negative: 13 },
  },
  {
    id: 'livpure-glo',
    name: 'Glo Star RO+UV+Mineraliser 7-Litre Water Purifier',
    brand: 'Livpure',
    category: 'Water Purifiers',
    categorySlug: 'water-purifiers',
    price: 12990,
    mrp: 17990,
    rating: 4.1,
    reviewCount: 5634,
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=600&q=80',/cdn/shop/products/Glo-Star-RO-UV-Mineraliser-7L.jpg',
    images: [
      'https://www.livpure.com/cdn/shop/products/Glo-Star-RO-UV-Mineraliser-7L.jpg',
    ],
    badge: 'Best Value',
    energyRating: '',
    specs: {
      'Purification Method': 'RO + UV + Mineraliser',
      'Storage Capacity': '7 Litres',
      'Purification Capacity': '15 Litres/hour',
      'TDS Reduction': 'Up to 1500 ppm inlet',
      'Mineraliser': 'Yes',
      'Digital Display': 'TDS Level',
      'Auto Shut-Off': 'Yes',
      'Installation': 'Wall Mounted',
      'Power': '30W',
      'Warranty': '1 Year Comprehensive',
    },
    highlights: [
      'Affordable price with premium features',
      'Mineraliser adds back essential minerals post-purification',
      'Digital display shows live TDS levels',
      'Compact design fits any kitchen size',
      'Made for Indian water conditions with TDS up to 1500 ppm',
    ],
    prices: [
      { store: 'Flipkart', price: 12990, url: 'https://www.flipkart.com/search?q=Livpure+Glo+Star+RO+UV+Water+Purifier', delivery: 'Free delivery in 3 days' },
      { store: 'Amazon', price: 13490, url: 'https://www.amazon.in/s?k=Livpure+Glo+Star+RO+UV+Water+Purifier', delivery: 'Free delivery in 3 days' },
      { store: 'Croma', price: 13990, url: 'https://www.croma.com/searchB?q=Livpure+Glo+Water+Purifier', delivery: 'Free delivery in 4 days' },
      { store: 'Reliance Digital', price: 13990, url: 'https://www.reliancedigital.in/search?q=Livpure+Glo+Water+Purifier', delivery: 'Free delivery in 5 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Harish Bandari', rating: 4, title: 'Great value for money', body: 'For under 13,000 this is unbeatable. Works perfectly in our Pune flat where TDS is around 800. The digital TDS display is very useful to track filter health. Livpure service is decent. Would definitely recommend for budget buyers.', date: '2024-02-05', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Usha Kumari', rating: 2, title: 'Cannot handle very high TDS', body: 'Our groundwater TDS is 1800 and the Livpure could not handle it - kept giving error beeps. They dont clearly mention the 1500 TDS limit in marketing. Had to return it and buy Kent which handles higher TDS. Check your water TDS before buying this.', date: '2024-03-20', sentiment: 'negative', verified: true },
    ],
    sentiment: { positive: 67, neutral: 18, negative: 15 },
  },
  {
    id: 'ifb-senator-8kg',
    name: 'Senator WXS 8 kg 5 Star Front Load Washing Machine',
    brand: 'IFB',
    category: 'Washing Machines',
    categorySlug: 'washing-machines',
    price: 44990,
    mrp: 56000,
    rating: 4.4,
    reviewCount: 1432,
    image: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&q=80',/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/s/e/senator-wxs-front.jpg',
    images: [
      'https://www.ifbappliances.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/s/e/senator-wxs-front.jpg',
    ],
    badge: 'Professional Grade',
    energyRating: '5 Star',
    specs: {
      'Capacity': '8 kg',
      'Type': 'Front Load',
      'Spin Speed': '1200 RPM',
      'Energy Rating': '5 Star BEE',
      'Wash Programs': '11',
      'Motor': 'Aqua Energie (Energy Efficient)',
      'Wi-Fi': 'No',
      'Steam Wash': 'No',
      'Cradle Wash': 'Yes',
      'Drum Material': 'Stainless Steel',
      'Water Level': 'Auto Water Level Sensor',
      'Warranty': '4 Years Comprehensive + 10 Years Motor',
    },
    highlights: [
      '4 Year comprehensive warranty - best in class',
      'Aqua Energie - converts hard water to soft water using electromagnets',
      '3D Wash System for 360° cleaning action',
      'Ball Valve Technology prevents water wastage',
      'IFB Express Wash - full 8kg load in 59 minutes',
    ],
    prices: [
      { store: 'Flipkart', price: 44990, url: 'https://www.flipkart.com/search?q=IFB+Senator+WXS+8kg+Front+Load+Washing+Machine', delivery: 'Free delivery in 3 days' },
      { store: 'Amazon', price: 45490, url: 'https://www.amazon.in/s?k=IFB+Senator+8kg+Front+Load+Washing+Machine', delivery: 'Free delivery in 4 days' },
      { store: 'Croma', price: 46990, url: 'https://www.croma.com/searchB?q=IFB+Senator+8kg+Washing+Machine', delivery: 'Same day delivery available' },
      { store: 'Reliance Digital', price: 46490, url: 'https://www.reliancedigital.in/search?q=IFB+Senator+8kg+Front+Load+Washing+Machine', delivery: 'Free delivery in 5 days' },
    ],
    reviews: [
      { id: 'r1', author: 'Chandra Bose', rating: 5, title: 'IFB is built for India', body: 'The Aqua Energie technology for hard water conversion is pure genius for an Indian market product. Our Chennai hard water was causing scale buildup in our LG machine. Switched to IFB 2 years ago and zero issues. The 4 year warranty speaks to their confidence in build quality.', date: '2024-01-18', sentiment: 'positive', verified: true },
      { id: 'r2', author: 'Anjali Sharma', rating: 2, title: 'IFB service is abysmal', body: 'The machine itself is good but IFB service in Lucknow is terrible. Had a small gasket issue and they took 3 weeks and 3 visits to fix it. Their spare parts are also overpriced. Good hardware but terrible service ecosystem.', date: '2024-03-28', sentiment: 'negative', verified: true },
    ],
    sentiment: { positive: 76, neutral: 12, negative: 12 },
  },
];

export const categories = [
  { name: 'TVs', slug: 'tvs', emoji: '📺', count: 127, description: 'Smart LED, OLED & QLED TVs' },
  { name: 'Refrigerators', slug: 'refrigerators', emoji: '❄️', count: 89, description: 'Single, Double Door & Side-by-Side' },
  { name: 'Washing Machines', slug: 'washing-machines', emoji: '🫧', count: 64, description: 'Front Load, Top Load & Semi-Auto' },
  { name: 'Dishwashers', slug: 'dishwashers', emoji: '🍽️', count: 32, description: 'Freestanding & Built-in Dishwashers' },
  { name: 'Air Conditioners', slug: 'air-conditioners', emoji: '💨', count: 98, description: 'Split, Window & Portable ACs' },
  { name: 'Microwaves', slug: 'microwaves', emoji: '🔥', count: 45, description: 'Solo, Grill & Convection Microwaves' },
  { name: 'Water Purifiers', slug: 'water-purifiers', emoji: '💧', count: 53, description: 'RO, UV & Gravity-Based Purifiers' },
  { name: 'Air Purifiers', slug: 'air-purifiers', emoji: '🌬️', count: 38, description: 'HEPA, UV & Activated Carbon Filters' },
  { name: 'Vacuum Cleaners', slug: 'vacuum-cleaners', emoji: '🧹', count: 41, description: 'Wet-Dry, Robot & Handheld Vacuums' },
  { name: 'Geysers', slug: 'geysers', emoji: '🚿', count: 57, description: 'Storage, Instant & Solar Geysers' },
];

export function getProductsByCategory(slug: string): Product[] {
  return products.filter(p => p.categorySlug === slug);
}

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getTrendingTVs(): Product[] {
  return products.filter(p => p.categorySlug === 'tvs').slice(0, 4);
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}

export function getDiscount(price: number, mrp: number): number {
  return Math.round(((mrp - price) / mrp) * 100);
}
